namespace Network.ProtocolStruct
{
    public enum CHCONNECTRESULT
    {
        CHCONNECT_SUCCESS,
        CHCONNCET_WRONGCH,
        CHCONNECT_WRONG_USER,
        CHCONNECT_UNKNOWNERROR,
        CHCONNECT_NOT_CONNECTABLE_TEAM,
        CHCONNECT_INVALID_PASSWORD,
        CHCONNECT_RESTRICTED_LEVEL,
        CHCONNECT_RESTRICTED_KD,
        CHCONNECT_RESTRICTED_BOTH_LEVEL_AND_KD
    }
    
    public enum CMMCHCONNECTRESULT
    {
        CMM_CHCONNECT_SUCCESS,
        CMM_CHCONNCET_WRONGCH,
        CMM_CHCONNECT_WRONG_USER,
        CMM_CHCONNECT_UNKNOWNERROR,
        CMM_CHCONNECT_INVALID_PASSWORD,
        CMM_CHCONNECT_RESTRICTED_LEVEL,
        CMM_CHCONNECT_RESTRICTED_KD,
        CMM_CHCONNECT_RESTRICTED_BOTH_LEVEL_AND_KD
    }
}