namespace Network.ProtocolStruct
{
    public enum GAMEENDREASON : byte
    {
        GAMEENDREASON_GAMEFINISHEDPROPERLY,
        GAMEENDREASON_TIMEOUT,
        GAMEENDREASON_GAMEFINISHEDABNORMALLY,
        GAMEENDREASON_GAMEFINISHEDABNORMALLY_VOIDGAME,
        GAMEENDREASON_GAMEFINISHED_AI_RESURRECTIONTIMEOUT
    }
}