namespace Network.ProtocolStruct
{
    public enum TOURROOM_STATE_R
    {
        TOUR_NONE,
        TOUR_BEFORE_GAMESTART,
        TOUR_GAMEPLAYING_FIRSTHALF,
        TOUR_HALFTIME_TEAMCHANGE,
        TOUR_HALFTIME,
        TOUR_GAMEPLAYING_SECONDHALF,
        TOUR_OVERTIME_TEAMCHANGE,
        TOUR_BEFORE_OVERTIME_GAME,
        TOUR_GAMEPLAYING_OVERTIME_FIRSTHALF,
        TOUR_OVERTIME_GAME_HALFTIME_TEAMCHANGE,
        TOUR_OVERTIME_GAME_HALFTIME,
        TOUR_GAMEPLAYING_OVERTIME_SECONDHALF,
        TOUR_FINISHED_GAME
    }
}