namespace Network.ProtocolStruct
{
    public enum BUYITEM_SERVER_RESULT
    {
        BUYITEM_SERVER_RESULT_NORMAL,
        BUYITEM_SERVER_RESULT_DONT_PROCESS_EXTRA_INFO
    }
    
    public enum BUYITEM
    {
        BUYITEM_SUCCESS,
        BUYITEM_NOMONEY,
        BUYITEM_FAIL,
        BUYITEM_SOMEFAIL,
#if USE_CFVIP_SYSTEM
        BUYITEM_ONLY_SPECIAL_USER,
#endif
        BUYITEM_DATEOVER,
        BUYITEM_NO_CLAN,
        BUYITEM_LIMIT_FAIL,
        BUYITEM_MY_INVEN_LIMIT_FAIL,
        BUYITEM_INVALID_RECOMMEND_ITEM,
        BUYITEM_UNQUALIFIED_FOR_RECOMMEND_ITEM,
        BUYITEM_FPOINT_INVALID_LOGTYPE,
        BUYITEM_FPOINT_INVALID_ITEM,
        BUYITEM_FPOINT_NO_FPOINT,
        BUYITEM_FPOINT_LIMIT_LEVEL,
        BUYITEM_FPOINT_CANT_DELAY,
        BUYITEM_FPOINT_OVERBUY,
        BUYITEM_AI_GACHA_LIMIT_FAIL, // US 19
        ENUM_18,
        ENUM_19,
        ENUM_20,
        BUYITEM_COUPON_EVENT_INVALID_INDEX,
        BUYITEM_COUPON_EVENT_NOT_STARTED,
        BUYITEM_COUPON_EVENT_ENDED,
        BUYITEM_COUPON_EVENT_FAIL,
        BUYITEM_COUPON_EVENT_ALREADY_USED,
        ENUM_26, // SomeFail
        MSZ_29626,
        BUYITEM_MPOINT_INCORRECT_INFO,
        BUYITEM_MPOINT_LIMIT_ITEM,
        BUYITEM_MPOINT_NO_MPOINT,
        BUYITEM_MPOINT_COOLDOWN,
        ENUM_34 = 34,
        ENUM_35 = 35,
        //ENUM_37 = 37 // EXCEED LIMIT
    }
}