namespace Network.ProtocolStruct
{
    public enum E_MATCH_TYPE
    {
        E_MATCH_TYPE_NOTCLAN_TEAMMATCH = 1,
        E_MATCH_TYPE_NOTCLAN_TEAMDEATHMATCH,
        E_MATCH_TYPE_NOTCLAN_GHOSTMATCH,
        E_MATCH_TYPE_NOTCLAN_DEATHMATCH,
        E_MATCH_TYPE_NOTCLAN_NANO,
        E_MATCH_TYPE_NOTCLAN_ESCAPE = 9,
        E_MATCH_TYPE_NOTCLAN_AI = 11,
        E_MATCH_TYPE_NOTCLAN_NANO3,
        E_MATCH_TYPE_NOTCLAN_NANO4 = 14,
        E_MATCH_TYPE_NOTCLAN_TEAMMATCH_DEATH = 7,
        E_MATCH_TYPE_NOTCLAN_SPECIAL = 6,
        E_MATCH_TYPE_NOTCLAN_NEW_MAP = 99,
        E_MATCH_TYPE_NOTCLAN_NONE = 10000,
        E_MATCH_TYPE_CLAN = 100
    }
}