namespace Network.ProtocolStruct
{
    public enum MMCONNECT_UNKNOWNERROR_DETAIL_INFO
    {
        MMCONNECT_UNKNOWNERROR_DEFAULT_VALUE,
        MMCONNECT_UNKNOWNERROR_FAIL_TO_REPORT_TO_LOGINSRV,
        MMCONNECT_UNKNOWNERROR_DB_ERROR_LOAD_CHARACTER_INFO,
        MMCONNECT_UNKNOWNERROR_QUERY_UPDATE_SACK_EXPIRED,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERINVEN_NOTINPCB,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERINVEN_NOTINPCB_2,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_EXPIRED_ITEM_INVEN,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_EXPIRED_ITEM_INVEN_2,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_EXIRED_CHARACTER,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_EXIRED_CHARACTER_2,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERCHAR,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERCHAR_2,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERSACK,
        MMCONNECT_UNKNOWNERROR_QUERY_SELECT_USERSACK_2,
        MMCONNECT_UNKNOWNERROR_DEFAULT_CHARACTER_ID,
        MMCONNECT_UNKNOWNERROR_MAIN_SACK,
        MMCONNECT_UNKNOWNERROR_COUPON_EVENT
    }
}