namespace Network.SharedFolder
{
    public enum ROUNDTYPE
    {
        ROUNDTYPE_NONE,
        ROUNDTYPE_TEAMMATCH,
        ROUNDTYPE_TEAMDEATHMATCH,
        ROUNDTYPE_HIDDEN,
        ROUNDTYPE_DEATHMATCH,
        ROUNDTYPE_NANO,
        ROUNDTYPE_SPECIAL,
        ROUNDTYPE_TEAMMATCH_DEATH, // Elimination
        ROUNDTYPE_CS_MATCH, // Elite S&D
        ROUND_TYPE_ESCAPE,
        ROUNDTYPE_TUTORIAL,
        ROUNDTYPE_AIMOD,
        ROUNDTYPE_NANO3,
        ROUNDTYPE_TRAINING_WEAPON,
        ROUNDTYPE_NANO4,
        ROUNDTYPE_WAVE,
        ROUNDTYPE_HIDDEN2_ELIMINATION,
        ROUNDTYPE_HIDDEN2_INFECTION,
        ROUNDTYPE_NANO5, // Mutant vs Ghost
        ROUNDTYPE_NANO6, // Mutant Knight
        ROUNDTYPE_SUPERSOLDIER_TD,
        ROUNDTYPE_LIGHT_TEAMMATCH, // Supression Mode
        ROUNDTYPE_SPY,
        ROUNDTYPE_CAPTAIN_MATCH,
        ROUNDTYPE_AIMOD2,
        ROUNDTYPE_SUPERSOLDIER_TM,
        ROUNDTYPE_AIBOT_TEAMDEATHMATCH,
        ROUNDTYPE_SHEEP_MODE,
        ROUNDTYPE_AIBOT_TEAMDEATHMATCH_MIX,
        ROUNDTYPE_KINGS_DEATHMATCH,
        ROUNDTYPE_TM2_MODE,
        ROUNDTYPE_AIMOD3,
        ROUNDTYPE_AIBOT_TEAMMATCH,
        ROUNDTYPE_CTC_MODE, // CoinBattle
        ROUNDTYPE_BIG_HEAD,
        ROUNDTYPE_ESCAPE_TEAMMATCH,
        ROUNDTYPE_WEAPONMASTER_DEATHMATCH,
        ROUNDTYPE_BATTLE_TEAMDEATHMATCH_MODE, // CN used
        ROUNDTYPE_BATTLE_OCCUPATION_MODE, // CN used
        ROUNDTYPE_BOSS_BATTLE,
        ROUNDTYPE_WEAPONMASTER_TEAMDEATHMATCH,
        ROUNDTYPE_GUESSME_MODE,
        ROUNDTYPE_BATTLE_ROYAL_DM,
        ROUNDTYPE_BATTLE_ROYAL_TD,
        ROUNDTYPE_BATTLE_ROYAL_DUO,
        ROUNDTYPE_AIM_MODE,
        ROUNDTYPE_STEALTH_BOMBING,
        ROUNDTYPE_GUESSME2_MODE,
        ROUNDTYPE_KNOCKBACK_MODE,
        ROUNDTYPE_HORROR_HIDE_AND_SEEK,
        ROUNDTYPE_ELITE_AI,
        ROUNDTYPE_MAX
    }
}