namespace Network.ProtocolStruct.Gacha
{
    public enum eGACHA_USE_WEAPON_PART
    {
        GACHA_USE_WEAPON_PART_SUCCESS,
        GACHA_NO_WEAPON_PART_ALL,
        GACHA_NO_WEAPON_PART_BODY,
        GACHA_NO_WEAPON_PART_HANDLE,
        GACHA_NO_WEAPON_PART_BUTTPLATE,
        GACHA_NO_WEAPON_PART_GUNBARREL,
        GACHA_USE_WEAPON_PART_NOITEM,
        GACHA_USE_WEAPON_PART_FAIL
    }
}